### ISSUE TITLE
ModuleNotFoundError: No module named 'get_resource_directory

### ISSUE THREAD

**Issue by donzef** [HewlettPackard/ansible-ilorest-role#11]
Module add_user_account returns ModuleNotFoundError: No module named 'get_resource_directory

Actually, only the modules without calling this get_resource_directory [kind of] work ! 

Is there a way to fix this error without commenting out the "from get_resource_directory import get_resource_directory"  and all related calls as it is done in several other modules ?

HPE's  ResourceDirectory feature is very useful for crawling the HPE's Redfish tree !

Thanks

**Comment by taroh77** [comment]
I added the `library` directory to `PYTHONPATH` and it worked.
```
export PYTHONPATH=/path/to/ansible-ilorest-role/library/
```

**Comment by samiron7567** [comment]
I found a workaround for this issue that really works. Because you are calling a python sub module via a module from Ansible, you must keep your sub module in desired directory recommended by Ansible. in this case, create a "module_utils" directory in the same location where you have your "library" directory. Next, move your sub module there and in your python module file mention something like, "`import ansible.module_utils.<SUB_MODULE> as <subname>`"

Ansible understand below:
`import ansible.module_utils.<SUB_MODULE> as <subname>`

Python understand below within same module directory:
`import <SUB_MODULE> as <subname>`

Let me know if that works.
